version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: java21
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_MULTIPLE_DATABASES: dev,staging
        POSTGRES_HOSTNAME: postgresql
        POSTGRES_PORT: 5432

    volumes:
      - ../..:/workspaces:cached
      #- /var/run/docker.sock:/var/run/docker.sock
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgresql18

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgresql18:
    image: postgres:18.1
    restart: always
    container_name: postgresql18
    shm_size: 128mb
    volumes:
      - ../pg-init-scripts:/docker-entrypoint-initdb.d
      - ../postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=dev,staging
      - MYSQL_INITDB_SKIP_TZINFO=1
    ports:
      - "5432:5432"
